
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BCONJ BCOR BD BE BIBS BL BT ECONJ ECOR ED EE EL ES ET ITEXT MT SEC SSEC SSSEC TEXTstatement : texttext : text textptext : TEXTptext : ptext TEXTtext : BT ptext ETtext : BL ptext ELtext : BCOR ptext ECORtext : BCONJ ptext ECONJtext : BE ptext EEtext : BD ptext EDtext : SEC ptext EStext : SSEC ptext EStext : SSSEC ptext EStext : ptext MTtext : BIBS ptext'
    
_lr_action_items = {'BT':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[3,3,-3,3,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BL':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[5,5,-3,5,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BCOR':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[6,6,-3,6,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BCONJ':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[7,7,-3,7,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BE':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[8,8,-3,8,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BD':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[9,9,-3,9,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'SEC':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[10,10,-3,10,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'SSEC':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[11,11,-3,11,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'SSSEC':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[12,12,-3,12,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'BIBS':([0,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[13,13,-3,13,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'TEXT':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,],[14,14,14,18,14,14,14,14,14,14,14,14,14,-3,14,18,-14,-4,18,18,18,18,18,18,18,18,18,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'$end':([1,2,14,15,17,18,27,28,29,30,31,32,33,34,35,36,],[0,-1,-3,-2,-14,-4,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'MT':([4,14,18,],[17,-3,-4,]),'ET':([14,16,18,],[-3,28,-4,]),'EL':([14,18,19,],[-3,-4,29,]),'ECOR':([14,18,20,],[-3,-4,30,]),'ECONJ':([14,18,21,],[-3,-4,31,]),'EE':([14,18,22,],[-3,-4,32,]),'ED':([14,18,23,],[-3,-4,33,]),'ES':([14,18,24,25,26,],[-3,-4,34,35,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'text':([0,2,15,],[2,15,15,]),'ptext':([0,2,3,5,6,7,8,9,10,11,12,13,15,],[4,4,16,19,20,21,22,23,24,25,26,27,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> text','statement',1,'p_statement_text','texlexparse.py',148),
  ('text -> text text','text',2,'p_text_text','texlexparse.py',152),
  ('ptext -> TEXT','ptext',1,'p_ptext_text','texlexparse.py',156),
  ('ptext -> ptext TEXT','ptext',2,'p_ptext_ptext_text','texlexparse.py',160),
  ('text -> BT ptext ET','text',3,'p_text_theorem','texlexparse.py',164),
  ('text -> BL ptext EL','text',3,'p_text_lemma','texlexparse.py',168),
  ('text -> BCOR ptext ECOR','text',3,'p_text_corollary','texlexparse.py',172),
  ('text -> BCONJ ptext ECONJ','text',3,'p_text_conjecture','texlexparse.py',176),
  ('text -> BE ptext EE','text',3,'p_text_example','texlexparse.py',180),
  ('text -> BD ptext ED','text',3,'p_text_definition','texlexparse.py',184),
  ('text -> SEC ptext ES','text',3,'p_text_sec','texlexparse.py',188),
  ('text -> SSEC ptext ES','text',3,'p_text_ssec','texlexparse.py',192),
  ('text -> SSSEC ptext ES','text',3,'p_text_sssec','texlexparse.py',196),
  ('text -> ptext MT','text',2,'p_text_mtbeg','texlexparse.py',200),
  ('text -> BIBS ptext','text',2,'p_text_bibend','texlexparse.py',204),
]
